### DISCUSSION TITLE
How to set up a jupyverse for a team

### DISCUSSION THREAD

**Discussion by oscar6echo** [jupyter-server/jupyverse#318] [Q&A]
This dicussion is a follow up from issue #301

**Comment by oscar6echo** [comment]
Let me clarify the objective and the context:

**Context**:  
AFAIK Jupyter comes in 3 flavors: 
+ Jupyter "Desktop" ie. the individual Jupyter Server - excellent but individual 
+ JupyterHub: ambitious initial idea but very complex to setup, demanding on the infrastructure, very expensive if many users
+ JupyterLite: super scalable and convenient but limited scope (some packages do not work) for the foreseeable future  

Now it seems there is a new kid on the block: Jupyverse. AFAIU it is a recent, modern version of Jupyter server and could maybe fill the gap I see in the Jupyter range to allow easy, convenient small scale teamwork.

**Objective**:  
Allow a small (<10 people) team of engineers in a corp env (quite constrained), typically Python and Jupyter users but without other IT skills, to launch and use a common jupyverse from one of their Win10 machine or from a Linux VM, in order to work independently and collaboratively.  

**Constraints**:
+ On a Win10 machine only conda/(micro)mamba is installed with access to conda-forge and pypi through artifactory, no docker, internet access through proxy. 
+ On a Linux VM sudo is available and internet access through proxy.  
+ However it can be assumed that a fief server/worker and theirs satellites (PostgreSQL DB, Redis) are self hosted on a corp kube cluster by an IT team, and one team member would have access to a tenant to manage other team members access rights, and the [OAuth provider](https://docs.fief.dev/configure/oauth-providers/#generic-openid) would be the corporate one.

**User access rights**:  
The jupyter [permissions](https://github.com/jupyter-server/jupyverse/issues/301#issuecomment-1579472469) mentionned in the issue #301 are necessary to provide full individual server Jupyter Lab experience. But it would be useful, arguably necessary, to add file system access rights per user or group of users along the lines described in the following tentative yaml:

```yml
# file access-config.json
---
# groups just for convenience
groups:
- name: all
  users:
  - user-a
  - user-b
# file system
# only paths mentionned are visible
folders:
# this folder would have notebooks used in real time collab
- path: "./shared"
  rights:
    readonly: []
    readwrite:
    - all
# this folder would have immutable reference notebooks and data files
- path: "./ref"
  rights:
    readonly:
    - all
    readwrite: []
# this is user-a private folder
- path: "./folder-a"
  rights:
    readonly: []
    readwrite:
    - user-a
# this is user-b private folder
- path: "./folder-b"
  rights:
    readonly: []
    readwrite:
    - user-b
```

Assuming this can be envisaged, I would think these rights should be encoded as fief permissions ? Or should it stays with jupyverse as a config file read upon start like below ?

```sh
jupyverse \
    --set auth_fief.base_url=https://jupyverse-XXXXX.fief.dev \
    --set auth_fief.client_id=XXXXXXXXXXXXXXXXXXXXXXXX \
    --set auth_fief.client_secret=XXXXXXXXXXXXXXXXXXXXXX \
    --set filesystem.access_config=access-config.json
```

Naturally these are blunt proposals for illustration only.

I would also be useful, I think, to allow such filesystem.access_config without fief so that a team of engineers in constrained corp env with zero IT support could work on same server for a few hours or a day.

In general the small team use case has potential in the corp env I'm sure.  
And this size limit may make some issues easy to solve e.g. who wants to collaborate with more than 5 people on a notebook, or maybe 10 on a text file ?

Food for thought.
